# -*- coding: utf-8 -*-
"""convert url to h264 video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlJHkXgPqUHGhnrqD8RWFyhUUbWlxNKU
"""

import shutil
from google.colab import files
!apt-get update
!apt-get install -y ffmpeg

url = "Enter ownload link here"
filename = 'Enter name of file plus extension'
output_file = filename.replace(".mkv", "-converted.mkv")

command = f"wget '{url}' -O '{filename}'"
!{command}

command = f"ffmpeg -i '{filename}' -c:v copy -c:a aac '{output_file}'"
!{command}

# Copy the file to Google Drive
import shutil
from google.colab import drive

drive.mount('/content/drive')
shutil.copy(output_file, f'/content/drive/MyDrive/Temp/{output_file}')